---
engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
exclude_paths:
  - demo/**
  - dist/**
  - test/**
  - Gruntfile.js
  - src/intro.js
  - src/outro.js
